# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5170f82490cc36632e49bc3303b4a4782137e6ce2eb95da8dbb050bc035d42f89a5a34084c1c5ae1e5d8d1dcfb3fd933114f45848ef9df26ab917b76b0cfa2aa

test:
  secret_key_base: eb775d4e3e15686a9331e3aec12c750ceef0d7aded5d5f0815d6f74ac7aa184f0b641f9b56d0d12ecfc7f8b29e2f2a49446f93eaa8d48e7f7e436c6bf68cc092

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
